// This file is auto-generated by the Caffeine build system.
// It provides type stubs for the backend actor interface.
import type { ActorSubclass } from "@dfinity/agent";
import type { Principal } from "@dfinity/principal";
import type { _SERVICE } from "../../backend/backend";

export type backendInterface = ActorSubclass<_SERVICE>;

export interface CreateActorOptions {
  agentOptions?: object;
  actorOptions?: object;
}

export class ExternalBlob {
  constructor(
    private bytes: Uint8Array,
    public onProgress?: (pct: number) => void,
  ) {}

  async getBytes(): Promise<Uint8Array> {
    return this.bytes;
  }

  static fromURL(url: string): ExternalBlob {
    const blob = new ExternalBlob(new Uint8Array());
    blob._url = url;
    return blob;
  }

  _url?: string;
}

export function createActor(
  _canisterId: string | Principal,
  _uploadFile?: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile?: (bytes: Uint8Array) => Promise<ExternalBlob>,
  _options?: CreateActorOptions,
): backendInterface {
  throw new Error("createActor: use createActorWithConfig instead");
}

export const canisterId: string = "";
